# Metrics for Multi-Class Baseline Models 

## Results for Baseline 1: Chance

In [2]:
import numpy as np
import os
import pandas as pd
from sklearn import metrics

In [22]:
chance_df = pd.read_csv('chance_df.csv')
chance_df.head()

pred  actual
0      right  center
1       left  center
2     center  center
3  leanright  center
4     center  center

In [25]:
y_pred = chance_df["pred"]
y_actual = chance_df["actual"]

In [27]:
# printing confusion matrix 
print(metrics.confusion_matrix(y_actual,y_pred))

# printing precision and recall, among other metrics 
print(metrics.classification_report(y_actual,y_pred,digits=4))

[[375 426 402 428 412]
 [418 397 387 395 412]
 [400 399 410 413 385]
 [406 416 381 393 380]
 [401 362 420 371 411]]
              precision    recall  f1-score   support

      center     0.1875    0.1836    0.1855      2043
    leanleft     0.1985    0.1976    0.1981      2009
   leanright     0.2050    0.2043    0.2046      2007
        left     0.1965    0.1989    0.1977      1976
       right     0.2055    0.2092    0.2073      1965

   micro avg     0.1986    0.1986    0.1986     10000
   macro avg     0.1986    0.1987    0.1986     10000
weighted avg     0.1985    0.1986    0.1986     10000



## Results for Baseline 2: Logistic Regression

In [12]:
# load df for baseline 2: logistic regression/NB classifier 
logit_df = pd.read_csv('pred_logit.csv')
logit_df.head()

Unnamed: 0 predicted_class actual_class
0           1           right       center
1           2          center       center
2           3           right       center
3           4       leanright       center
4           5          center       center

In [14]:
y_pred1 = logit_df["predicted_class"]
y_actual1 = logit_df["actual_class"]

In [15]:
print(metrics.confusion_matrix(y_actual1,y_pred1))
print(metrics.classification_report(y_actual1,y_pred1,digits=4))

[[ 994  239  238  345  227]
 [ 293  622  463  397  234]
 [ 296  333  874  268  236]
 [ 174  171  226 1167  238]
 [ 162  166  197  268 1172]]
              precision    recall  f1-score   support

      center     0.5180    0.4865    0.5018      2043
    leanleft     0.4063    0.3096    0.3514      2009
   leanright     0.4374    0.4355    0.4365      2007
        left     0.4773    0.5906    0.5279      1976
       right     0.5562    0.5964    0.5756      1965

   micro avg     0.4829    0.4829    0.4829     10000
   macro avg     0.4790    0.4837    0.4786     10000
weighted avg     0.4789    0.4829    0.4781     10000

